backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use common\models\LoginForm;
use yii\filters\VerbFilter;
use yii\helpers\Url;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionIndex() {
        return $this->render('index');
    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use Yii;
use yii\data\ActiveDataProvider;
use common\models\User;
use common\models\Order;
use common\models\ReceptionTime;
use common\models\ReceptionDay;
use common\helpers\Browser;

use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\NotFoundHttpException;
use yii\web\Controller;
use \yii\web\Response;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\helpers\Url;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                //'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex() {
	   //$this->redirect(Url::home().'control-panel');
        return $this->render('index');
    }

    public function actionAbout() {
        return $this->render('about');
    }
    
}

frontend/controllers/SliderController.php
<?php

namespace frontend\controllers;

use Yii;
use common\models\Slider;
use common\models\Image;
use common\models\SliderSearch;

use common\helpers\ZipHelper;
use common\helpers\UtilsHelper;
use yii\helpers\FileHelper;
use yii\helpers\Url;

use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\UploadedFile;

use yii\filters\VerbFilter;

/**
 * SliderController implements the CRUD actions for Slider model.
 */
class SliderController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Slider models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new SliderSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Slider model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Slider model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Slider();

        if ($model->load(Yii::$app->request->post())) {
            $model->pdfFile = UploadedFile::getInstance($model, 'pdfFile');
            if ($model->save()) {
                $path = Yii::getAlias('@uploads') . '/' . $model->id . '/';
                if (FileHelper::createDirectory($path)) {
                    if ($model->upload($path)) {
                        $document = new \Imagick($path . $model->id . '.pdf');
                        $count = $document->getNumberImages();
                        if ($count <= 50) {
                            if (FileHelper::createDirectory($path . 'images/')) {
                                for ($x = 1; $x <= $document->getNumberImages(); $x++) {
                                    $document->previousImage();
                                    $imageName = 'img'.$count.'.jpeg';
                                    $image = new Image();
                                    $image->name = $imageName;
                                    $image->slider_id = $model->id;
                                    $image->image_link = Url::home(true) . 'uploads/' . $model->id . '/images/' . $imageName;
                                    if ($image->save()) {
                                        $document->writeImage($path . 'images/' . 'img'.$count.'.jpeg');
                                        $count--;
                                    }
                                }

                                //открыть файл, если не существует, то создать его
                                $fp = fopen($path . "index.html", "w");
                                 
                                //записать в файл сгенерированную по шаблону страницу
                                fwrite($fp, $this->renderPartial('_slider_index', ['model' => $model]));
                                 
                                //закрыть файл
                                fclose($fp);

                                UtilsHelper::recurse_copy(Yii::getAlias('@uploads') . '/assets', Yii::getAlias('@uploads') . '/' . $model->id . '/assets');

                                //удалить pdf файл из директории слайдера
                                unlink($path . $model->id . '.pdf');

                                return $this->redirect(['view', 'id' => $model->id]);
                            } else {
                                Yii::$app->session->setFlash('error', 'Не удалось создать директорию для изображений, попробуйте еще раз.');
                                $this->findModel($model->id)->delete();
                                FileHelper::removeDirectory($path);
                                return $this->render('create', [
                                    'model' => $model,
                                ]);
                            }
                        } else {
                            Yii::$app->session->setFlash('error', 'Количество страниц pdf файла не должно превышать 50.');
                            $this->findModel($model->id)->delete();
                            FileHelper::removeDirectory($path);
                            return $this->render('create', [
                                'model' => $model,
                            ]);
                        }
                    } else {
                        Yii::$app->session->setFlash('error', 'Не удалось загрузить файл pdf.');
                        $this->findModel($model->id)->delete();
                        FileHelper::removeDirectory($path);
                        return $this->render('create', [
                            'model' => $model,
                        ]);
                    }
                } else {
                    Yii::$app->session->setFlash('error', 'Не удалось создать директорию слайдера, попробуйте еще раз');
                    $this->findModel($model->id)->delete();
                    return $this->render('create', [
                        'model' => $model,
                    ]);
                }
            } else {
                Yii::$app->session->setFlash('error', 'Не удалось сохранить слайдер, попробуйте еще раз');
                return $this->render('create', [
                    'model' => $model,
                ]);
            }                  
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Slider model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    /*public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }*/

    /**
     * Deletes an existing Slider model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
    *
    * Метод для выгрузки архива со слайдером
    * Сгенерированный архив хранится в папке слайдера 30 минут, по истечении которых удаляется из папки слайдера cron-планировщиком
    *
    */
    public function actionDownloadSlider($id) {
        $model = $this->findModel($id);
        $path = Yii::getAlias('@uploads') . '/' . $model->id . '/' . $model->id . '.zip';
        if (!file_exists($path)) {
            $za = new ZipHelper;
            $res = $za->open($path, \ZipArchive::CREATE);
            $za->addDir(Yii::getAlias('@uploads') . '/' . $model->id, basename(Yii::getAlias('@uploads') . '/' . $model->id));
            $za->close();
        } 

        //установить заголовок ответа и отдать архив
        header("Content-Disposition: attachment; filename=\"".basename($path)."\"");
        header("Content-Length: ".filesize($path));
        readfile($path);
    }

    /**
     * Finds the Slider model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Slider the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Slider::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

frontend/views/site/about.php
<?php

/* @var $this yii\web\View */

$this->title = 'О сервисе';
?>
<div class="site-about" style="text-align: justify;">
		<h1>Конвертер PDF в HTML слайдер</h1>
		<p>Приложение представляет собой конвертер PDF-файлов в HTML-слайдер.</p>
		<p>На странице с созданным слайдером доступно действие «Скачать», при нажатии на которую скачивается zip архив, содержащий:</p>
		<ul>
			<li>index.html, который содержит слайдер;</li>
			<li>папку images, в которой хранятся изображения, конвертированные из PDF;</li>
			<li>папку assets, в которой хранятся необходимые ресурсы, например JS- библиотека слайдера.</li>
		</ul>
		<p>Требования к загружаемому файлу:</p>
		<ul>
			<li>Количество страниц – не больше 20;</li>
			<li>Размер файла – не более 50 Мб.</li>
		</ul>
    	<p>Также в приложении реализован REST api метод для получения списка ссылок изображений конкретного слайдера (по его id) для генерации кастомных слайдеров на сторонних сайтах (json).</p>
		<p>Пример обращения к методу: http://62.109.10.181/control-panel/api/slider/get-slider/{id}</p>
		<p>REST API реализован в отдельном модуле api</p>
</div>

frontend/views/site/closed.php
<?php

$this->title = 'Запись на личный приём к Главе администрации';
?>

<div class="row text-center">
    <div class="col-md-12">
        <div class="alert alert-warning block-shadow" role="alert">
            <p>
                Электронная запись на личный прием к Главе администрации закрыта!
            </p>
        </div>
    </div>
</div>

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>

<div class="container">
    <div class="site-error site-page">

        <h1><?= Html::encode($this->title) ?></h1>

        <div class="alert alert-danger">
            <?= nl2br(Html::encode($message)) ?>
        </div>

        <p>
            The above error occurred while the Web server was processing your request.
        </p>
        <p>
            Please contact us if you think this is a server error. Thank you.
        </p>

    </div>
</div>

frontend/views/site/index.php
<?php

/* @var $this yii\web\View */
use yii\helpers\Html;

$this->title = 'Главная страница';
?>
<div class="site-index">
	<div class="jumbotron">
		<h1>Конвертер PDF-файла в HTML слайдер</h1>
		<p>...</p>
		<p>
			<?= 
				Html::a('Создать слайдер!', ['/slider/create'], [
                                'title'=>'Создать слайдер!',
                                'class' => 'btn btn-primary btn-lg'
                            ]
                        )
            ?>
		</p>
	</div>
</div>

frontend/views/site/message.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

?>

<div class="container">

        <div class="alert alert-<?= ($type) ? ($type) : ('undefined') ?>">
            <?= nl2br(Html::encode($message)) ?>
        </div>

</div>

frontend/views/site/old-browser.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

$this->title = 'Используется старая версия браузера';
?>

<div class="row text-center">
    <div class="col-md-12">
        <div class="alert alert-warning block-shadow" role="alert">
            <p>
                Вы используете старую версию браузера!
            </p>
        </div>
    </div>
</div>

frontend/views/site/success.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = 'Вы записаны на приём к Главе администрации';
?>